apache:
  image: nginx
  replicas: 1
  servicePort: 80
  
tomcat:
  image: tomcat:9.0
  replicas: 1
  servicePort: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: www.httpd.com
      paths:
        - path: /
          pathType: ImplementationSpecific

serviceAccount:
  create: true
  automount: true


service:
  port: 80
