apache:
  image: nginx:latest
  replicas: 5
  servicePort: 80
  tag: v1
  
tomcat:
  image: tomcat:9.0
  replicas: 5
  servicePort: 8080
  tag: v1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  namespace: tomcat
  className: "nginx"
  annotations: {}
  hosts:
    - host: www.httpd.com
      paths:
        - path: /
          pathType: ImplementationSpecific

serviceAccount:
  create: true
  automount: true


service:
  port: 80
