apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    Listen 80

    ServerName localhost

    <VirtualHost *:80>
        ProxyPass "/" "http://tomcat:8080/"
        ProxyPassReverse "/" "http://tomcat:8080/"
    </VirtualHost>

 
