apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: {{ .Values.apache.replicas }}
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: {{ .Values.apache.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/apache2/conf/httpd.conf
              subPath: httpd.conf
      volumes:
        - name: config-volume
          configMap:
            name: apache-config

