apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pvc
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /share_4514213e_fe5b_4cd4_bc78_8aa193b06f4b/tomcat_data01
    server: 172.26.0.89
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ktc-nfs-client-ssd
  volumeMode: Filesystem
