apiVersion: v1
kind: PersistentVolume
  name: tomcat-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: /share_f46ad59c_02e1_4964_981c_096e1c82b45c/tomcat_data01
    server: 172.26.0.119
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ktc-nfs-client
  volumeMode: Filesystem
