apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ktc-nfs-client
  volumeMode: Filesystem
  volumeName: nfs-pvc

