apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
spec:
  replicas: {{ .Values.tomcat.replicas }}
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: {{ .Values.tomcat.image }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tomcat-config
              mountPath: /usr/local/tomcat/webapps/ROOT
      volumes:
        - name: tomcat-config
          persistentVolumeClaim:
            claimName: nfs-pvc-pvc
